### ISSUE TITLE
Custom qualifier

### ISSUE THREAD

**Issue by tj** [apex/invoke#1]
For locking in a version

**Comment by mthenw** [comment]
Do you have any idea how to implement that? I could take care of it.

**Comment by tj** [comment]
I guess with the current API we'd need something like `invoke.InvokeSyncQualifier` and move the [current stuff](https://github.com/apex/invoke/blob/master/invoke.go#L63-L93) into that func, and maybe `invoke.SyncQualifier()` to match w/ default client.

Since I didn't set them up to accept params :D

**Comment by mthenw** [comment]
`func InvokeSyncQualifier(client Lambda, name, qualifier string, in, out interface{}) error {`
or 
`func InvokeSyncQualifier(client Lambda, name string, in, out interface{}, qualifier string) error {`
?

Second one looks weird :)

**Comment by tj** [comment]
+1 for the first, and here's to hoping we don't need more params later hahaha

**Comment by mthenw** [comment]
> and here's to hoping we don't need more params later

dream of every developer :D
