### ISSUE TITLE
Usage with up?

### ISSUE THREAD

**Issue by xtuc** [apex/invoke#3]
My architecture is: one index process and one API that can submit work into it.

Currently both services use `up`, I was wondering how I could use this project (invoke) from the API to communicate with the indexing process?

AFAIK either I fake a HTTP request to use the HTTP server in `up` or I remove the HTTP server (is that possible with `up`?). 

Note that I could run the indexing process synchronously before the response from the API, but that's not ideal. 

Thanks!

**Comment by tj** [comment]
Ahh yea Up is focused on http so you'd have to send a regular http request, right now it's sort of either you use apex/apex for FaaS or apex/up for HTTP, some day they may be combined but it seems like a decent separation of concerns for now

**Comment by xtuc** [comment]
Ok, I used apex/apex, thanks for the clarification!
